spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBz21sNterCWoPRnmmow+Mrzvm4hRKZFzpS2qvIUgFZLWlkGBzGopdlvcGXTMDqaczDDRzsYbrVSLKn8PNRK61sioOjchhJcDiSdRu0vyt9lyC7c7wsV69kD9IQn3SVaEKCaB+f4SLKmfL1LNEN6ELBaU54kLisOvrJjKGOiGg3nJNyR+iFoCTfecROYF10w61tNVt/cAVFodPrX4msASYgE8QrtDZwfbxl/GCoK+luOdA74gjEHX+FjH2OvKqJelqcu1pit7O5wIgD15fxm+N+yDj3iHr3X1EcZlCUr6hKF/P30XKEPl8hSqy+lGxSv7FEUyPtRtyvuVC2wSAktAYobObVKSzX/9JSS87bUh8APwPFQZArGujFuXL1OsmSHlg='

token:
  expiration_time: 86400000
  secret: '{cipher}AQCuGWoj9d9VLxHUH4Ma0RbTh1YS8m2AEBXCpf16FpTyTHokxnRpwEZP7JKbMNTmEKULfqFgk/x4Sh1whRpYtze5QG9uwBj/P0Gaswu4UKwTrb4xOaLV9EqhFjspauUF9aWFWwxqBcYA+Afkuk1V78xyJkbH9oEjU/bftq2Nm9VIP7t2n9fDuywmPqYH/yKZslbT3/21lhDSkv1QcwQKUfhztrwwyGxiLhw2oKeuwcgrbIrVEp3sHst7Mau2BWhRj7FhYgWHHIhblLPV3+qqzlUB42vzjOoE2/RmklePv8IC7qqgFBueCRSeJZ0duno0x79QdR4RqaLoQbMSAiWDVTn6BvUc2VE9KwVUEX0YNWADWH6xGhTmqdOqWeOV05XffAco2C4+fVy99+vD5Kc24XzQ'

gateway:
  ip: 172.18.0.5

order_service:
  # url: http://127.0.0.1:8000/order-service/%s/orders
  url: http://order-service/order-service/%s/orders # @LoadBalanced 를 통해 ip가 아닌 microservice name으로 접근 가능
  exception:
    order_is_empty: No order Items.
